import { FormEvent, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "../index.css";

type Project = { id:number; title:string; description:string; tags:string[]; video:string; year:string };
const KEY="bovano_admin_token";
function Admin(){
 const [token,setToken]=useState(sessionStorage.getItem(KEY)||""),[password,setPassword]=useState(""),[projects,setProjects]=useState<Project[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const load=async()=>{const r=await fetch("/api/projects",{cache:"no-store"});if(r.ok)setProjects(await r.json())}; useEffect(()=>{load()},[]);
 async function login(e:FormEvent){e.preventDefault();const r=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})});const d=await r.json();if(!r.ok)return setMessage(d.error||"Помилка");sessionStorage.setItem(KEY,d.token);setToken(d.token);setPassword("");}
 async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,input=form.elements.namedItem("video") as HTMLInputElement,file=input.files?.[0];if(!file)return setMessage("Обери відео.");setBusy(true);setMessage(`Завантаження ${(file.size/1024/1024).toFixed(1)} MB…`);const r=await fetch("/api/admin/projects",{method:"POST",headers:{"x-admin-token":token},body:new FormData(form)});const d=await r.json().catch(()=>({}));setBusy(false);if(!r.ok)return setMessage(d.error||"Не вдалося завантажити");form.reset();await load();setMessage("Відео опубліковано.")}
 async function remove(id:number){if(!confirm("Видалити цей проєкт?"))return;const r=await fetch(`/api/admin/projects/${id}`,{method:"DELETE",headers:{"x-admin-token":token}});if(r.ok){await load();setMessage("Видалено")}}
 return <main className="min-h-screen max-w-4xl mx-auto p-6 md:p-10"><p className="text-sm tracking-widest uppercase text-[var(--color-accent)] mb-2">BOVANO</p><h1 className="text-3xl font-bold mb-2">Керування портфоліо</h1><p className="text-[var(--color-text-secondary)] mb-8">Завантажуй великі відео — клієнт дивиться їх прямо на one-page сайті.</p>{!token?<form onSubmit={login} className="max-w-md border border-[var(--color-border)] rounded-2xl p-6 bg-[var(--color-surface)]"><label className="block text-sm mb-2">Пароль адміністратора</label><input required value={password} onChange={e=>setPassword(e.target.value)} type="password" className="w-full rounded-xl bg-[var(--color-surface-2)] border border-[var(--color-border)] p-3 mb-4"/><button className="rounded-xl px-5 py-3 bg-[var(--color-accent)] text-black font-semibold">Увійти</button></form>:<><form onSubmit={upload} className="border border-[var(--color-border)] rounded-2xl p-6 bg-[var(--color-surface)] space-y-4"><input name="title" required placeholder="Назва проєкту" className="w-full rounded-xl bg-[var(--color-surface-2)] border border-[var(--color-border)] p-3"/><textarea name="description" placeholder="Короткий опис" rows={3} className="w-full rounded-xl bg-[var(--color-surface-2)] border border-[var(--color-border)] p-3"/><input name="tags" placeholder='Теги JSON: ["Motion","VFX"]' className="w-full rounded-xl bg-[var(--color-surface-2)] border border-[var(--color-border)] p-3"/><input name="year" placeholder="2026" className="w-full rounded-xl bg-[var(--color-surface-2)] border border-[var(--color-border)] p-3"/><input name="video" required type="file" accept="video/mp4,video/webm,video/quicktime" className="w-full p-3 border border-dashed border-[var(--color-border)] rounded-xl"/><button disabled={busy} className="rounded-xl px-5 py-3 bg-[var(--color-accent)] text-black font-semibold disabled:opacity-50">{busy?"Завантаження…":"Опублікувати відео"}</button></form>{message&&<p className="my-4 text-sm text-[var(--color-text-secondary)]">{message}</p>}<div className="mt-8 space-y-3">{projects.map(p=><div key={p.id} className="flex items-center gap-4 border border-[var(--color-border)] rounded-xl p-4 bg-[var(--color-surface)]"><div className="min-w-0 flex-1"><div className="font-medium truncate">{p.title}</div><div className="text-xs text-[var(--color-muted)]">{p.year}</div></div><button onClick={()=>remove(p.id)} className="text-sm text-red-300">Видалити</button></div>)}</div></>}</main>
}
createRoot(document.getElementById("root")!).render(<Admin/>);
